#!/usr/bin/env python3
# -----------------------------------------------------------------------------
# nestwork hook installer for Kimi Code
#
# Idempotently registers SessionStart / PreToolUse / PostToolUse / Stop hooks
# in ~/.kimi-code/config.toml. Uses comment markers so re-running the installer
# replaces the previous nestwork block instead of appending duplicates.
#
# Usage:
#   _kimi_hooks.py <config.toml> <nestwork_path> <host> <agent_id>
# -----------------------------------------------------------------------------

import os
import sys

BEGIN_MARK = "# === nestwork hooks begin ==="
END_MARK   = "# === nestwork hooks end ==="


def build_hooks(nestwork_path: str, host: str, agent_id: str) -> str:
    hook_script   = f"{nestwork_path}/scripts/hooks/nestwork.sh"
    session_start = f"{nestwork_path}/scripts/hooks/session-start.sh"

    start_cmd = f"bash {session_start} {host} {agent_id}"
    pre_cmd  = f"bash {hook_script} pre {host} {agent_id}"
    post_cmd = f"bash {hook_script} post {host} {agent_id}"
    stop_cmd = f"bash {hook_script} stop {host} {agent_id}"

    return f"""{BEGIN_MARK}
# Auto-generated by nestwork. Do not edit between these marks.

[[hooks]]
event = "SessionStart"
command = "{start_cmd}"
timeout = 10

[[hooks]]
event = "PreToolUse"
matcher = "Write|Edit"
command = "{pre_cmd}"
timeout = 10

[[hooks]]
event = "PostToolUse"
matcher = "Write|Edit"
command = "{post_cmd}"
timeout = 30

[[hooks]]
event = "Stop"
command = "{stop_cmd}"
timeout = 30

{END_MARK}
"""


def strip_existing_block(content: str) -> str:
    while True:
        begin = content.find(BEGIN_MARK)
        if begin == -1:
            break
        end = content.find(END_MARK, begin)
        if end == -1:
            # Marker begin without end -- strip from begin to EOF (should not happen)
            content = content[:begin]
            break
        # Remove the whole block including surrounding blank lines
        before = content[:begin]
        after = content[end + len(END_MARK):]
        # Collapse multiple trailing/leading blank lines into one
        before = before.rstrip() + "\n"
        after = after.lstrip()
        content = before + ("\n" + after if after else "")
    return content


def main() -> int:
    if len(sys.argv) < 5:
        print("usage: _kimi_hooks.py <config.toml> <nestwork_path> <host> <agent_id>", file=sys.stderr)
        return 2

    config_path   = sys.argv[1]
    nestwork_path = sys.argv[2].replace("\\", "/").rstrip("/")
    host          = sys.argv[3]
    agent_id      = sys.argv[4]

    os.makedirs(os.path.dirname(config_path) or ".", exist_ok=True)

    existing = ""
    if os.path.exists(config_path):
        with open(config_path, encoding="utf-8") as f:
            existing = f.read()

    content = strip_existing_block(existing)
    block = build_hooks(nestwork_path, host, agent_id)

    if content and not content.endswith("\n"):
        content += "\n"
    content = content.rstrip() + "\n\n" + block

    with open(config_path, "w", encoding="utf-8") as f:
        f.write(content)

    print(f"nestwork hooks registered in {config_path} for {host}/{agent_id}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
