#!/usr/bin/env bash
# Nestwork agent mailbox — read messages addressed to me (Tier 0/1).
# Scans every agent's outbox, selects messages where to == me (or to == all),
# skips ones already recorded in my seen list.
#
# Usage:
#   read.sh                  print unread to stdout
#   read.sh --mark           print unread, then record them as seen
#   read.sh --write <file>   write unread into <file> (for session-start
#                            injection); deletes <file> when there is nothing
#                            unread. Does NOT mark as seen — the agent marks
#                            after it has actually acted on the messages.
#
# Seen state lives in git-ignored agents/<self>/local/comms/seen.txt so that
# marking messages read never creates commits on main. A legacy committed
# agents/<self>/comms/seen.txt (pre v0.7) is imported on first run; you may
# `git rm` the legacy file afterwards.
#
# "Who am I" is resolved from NESTWORK_SELF, else ~/.nestwork_host +
# ~/.nestwork_id_claude. Other tool-chains: export NESTWORK_SELF=<host>/<agent-id>.
set -euo pipefail

ROOT="$(git rev-parse --show-toplevel)"
SELF="${NESTWORK_SELF:-$(cat ~/.nestwork_host)/$(cat ~/.nestwork_id_claude 2>/dev/null || true)}"
case "$SELF" in */) echo "ERROR: cannot resolve agent id; set NESTWORK_SELF=host/agent" >&2; exit 1;; esac

SEEN="$ROOT/agents/$SELF/local/comms/seen.txt"
LEGACY_SEEN="$ROOT/agents/$SELF/comms/seen.txt"
mkdir -p "$(dirname "$SEEN")"
if [ ! -f "$SEEN" ] && [ -f "$LEGACY_SEEN" ]; then
  cp "$LEGACY_SEEN" "$SEEN"
fi
touch "$SEEN"

MARK=0; WRITE=""
case "${1:-}" in
  --mark)  MARK=1 ;;
  --write) WRITE="${2:?usage: read.sh --write <file>}" ;;
  "")      ;;
  *)       echo "usage: read.sh [--mark | --write <file>]" >&2; exit 2 ;;
esac

buf=""; found=0
shopt -s nullglob
for f in "$ROOT"/agents/*/*/outbox/*.md; do
  to=$(sed -n 's/^to:[[:space:]]*//p' "$f" | head -1)
  [ "$to" = "$SELF" ] || [ "$to" = "all" ] || continue
  id=$(sed -n 's/^id:[[:space:]]*//p' "$f" | head -1)
  grep -qxF "$id" "$SEEN" && continue
  found=$((found+1))
  buf+="============================================================"$'\n'
  buf+="$(cat "$f")"$'\n\n'
  [ "$MARK" = 1 ] && echo "$id" >> "$SEEN"
done

if [ -n "$WRITE" ]; then
  if [ "$found" -gt 0 ]; then
    mkdir -p "$(dirname "$WRITE")"
    {
      printf '# 📨 Agent mailbox — %d unread message(s) for %s\n\n' "$found" "$SELF"
      printf '> Auto-generated by the session-start hook from other agents'\'' outboxes.\n'
      printf '> After acting on these, mark them read: bash scripts/comms/read.sh --mark\n\n'
      printf '%s' "$buf"
    } > "$WRITE"
  else
    rm -f "$WRITE"
  fi
  exit 0
fi

if [ "$found" = 0 ]; then echo "(no unread messages for $SELF)"; else printf '%s' "$buf"; fi
[ "$MARK" = 1 ] && [ "$found" -gt 0 ] && echo ">> marked $found message(s) as seen"
exit 0
