#!/usr/bin/env python3
"""Generate or check the topic index inside a memory scope's memory.md.

A memory scope is `shared/` or `agents/<host>/<agent-id>/`. A scope opts in to
topic storage (AGENTS.md section 6) by placing the index markers in its
`memory.md`. Every topic file in an opted-in scope carries front matter:

    ---
    description: <when an agent should read this file>
    updated: YYYY-MM-DD
    ---

The block between the markers is generated from that front matter, so the
routing table cannot drift from the files it describes. Text outside the
markers is preserved. Scopes without markers are left untouched (legacy
single-file memory keeps working).
"""
import argparse
import re
import sys
from pathlib import Path

BEGIN = "<!-- nestwork:topic-index:begin -->"
END = "<!-- nestwork:topic-index:end -->"
NOTE = "<!-- generated by scripts/maintenance/memory-index.py; edit topic front matter, not this block -->"

# Paths inside a scope that are never topic files.
RESERVED_FILES = {"memory.md", "resident.md"}
RESERVED_DIRS = {"outbox", "local", "carryover", "comms", "inbox", "archive"}
MAX_DEPTH = 2  # <topic>.md or <topic>/<subtopic>.md

TOPIC_WARN_BYTES = 16384
TOPIC_MAX_BYTES = 32768
INDEX_WARN_BYTES = 8192
DESCRIPTION_WARN_CHARS = 300


def parse_front_matter(text):
    if not text.startswith("---\n"):
        return {}
    end = text.find("\n---", 4)
    if end == -1:
        return {}
    fields = {}
    for line in text[4:end].splitlines():
        key, sep, value = line.partition(":")
        if sep and key.strip() and not line.startswith((" ", "\t")):
            fields[key.strip()] = value.strip().strip('"').strip("'")
    return fields


def topic_files(scope):
    for path in sorted(scope.rglob("*.md")):
        rel = path.relative_to(scope)
        if rel.name in RESERVED_FILES and len(rel.parts) == 1:
            continue
        if any(part in RESERVED_DIRS or part.startswith((".", "_")) for part in rel.parts):
            continue
        yield path, rel


def collect(scope):
    """Return (entries, problems, warnings) for one scope."""
    entries, problems, warnings = [], [], []
    for path, rel in topic_files(scope):
        name = rel.as_posix()
        if len(rel.parts) > MAX_DEPTH:
            problems.append(f"{name}: nested deeper than {MAX_DEPTH} levels")
            continue
        text = path.read_text(encoding="utf-8")
        size = len(text.encode("utf-8"))
        meta = parse_front_matter(text)
        description = meta.get("description", "")
        if not description:
            problems.append(f"{name}: missing `description` front matter (invisible to retrieval)")
            continue
        if size > TOPIC_MAX_BYTES:
            problems.append(f"{name}: {size} bytes exceeds {TOPIC_MAX_BYTES}; split it into {rel.with_suffix('').as_posix()}/")
        elif size > TOPIC_WARN_BYTES:
            warnings.append(f"{name}: {size} bytes is over the {TOPIC_WARN_BYTES}-byte soft limit")
        if len(description) > DESCRIPTION_WARN_CHARS:
            warnings.append(f"{name}: description longer than {DESCRIPTION_WARN_CHARS} chars")
        entries.append((name, description, meta.get("updated", ""), size))
    return entries, problems, warnings


def render(entries):
    lines = [BEGIN, NOTE, ""]
    for name, description, updated, size in entries:
        facts = ", ".join(x for x in (updated, f"{size / 1024:.1f} KB") if x)
        lines.append(f"- [`{name}`]({name}) — {description} ({facts})")
    if not entries:
        lines.append("_No topic files yet._")
    lines += ["", END]
    return "\n".join(lines)


def splice(memory_text, block):
    start = memory_text.index(BEGIN)
    stop = memory_text.index(END, start) + len(END)
    return memory_text[:start] + block + memory_text[stop:]


def opted_in_scopes(root):
    candidates = [root / "shared", *sorted(root.glob("agents/*/*"))]
    for scope in candidates:
        memory = scope / "memory.md"
        if memory.is_file() and BEGIN in memory.read_text(encoding="utf-8"):
            yield scope


def process(root, scope, check):
    memory = scope / "memory.md"
    label = scope.relative_to(root).as_posix()
    text = memory.read_text(encoding="utf-8") if memory.is_file() else ""
    if BEGIN not in text or END not in text:
        print(f"SKIP {label}: memory.md has no topic-index markers")
        return 1 if check else 0

    entries, problems, warnings = collect(scope)
    block = render(entries)
    updated = splice(text, block)
    for warning in warnings:
        print(f"WARN {label}/{warning}")
    if len(block.encode("utf-8")) > INDEX_WARN_BYTES:
        print(f"WARN {label}/memory.md: index block over {INDEX_WARN_BYTES} bytes; consolidate topics")
    for problem in problems:
        print(f"FAIL {label}/{problem}")

    if check:
        if updated != text:
            problems.append("stale")
            print(f"FAIL {label}/memory.md: index is stale; run scripts/maintenance/memory-index.py")
    elif updated != text:
        memory.write_text(updated, encoding="utf-8")
        print(f"UPDATED {label}/memory.md ({len(entries)} topics)")
    if not problems:
        print(f"OK {label}: {len(entries)} topics")
    return int(bool(problems))


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("scopes", nargs="*", type=Path,
                        help="Scope directories relative to --root (default: every opted-in scope).")
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[2])
    parser.add_argument("--check", action="store_true",
                        help="Do not write; fail if an index is stale or a topic file is invalid.")
    args = parser.parse_args()
    root = args.root.resolve()
    scopes = [(root / s).resolve() for s in args.scopes] or list(opted_in_scopes(root))
    failures = sum(process(root, scope, args.check) for scope in scopes)
    return int(failures > 0)


if __name__ == "__main__":
    sys.exit(main())
